base:
  version: VERSION
  css:
    theme:
      assets/css/prodigious.style.css: {}
  js:
    bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js: {}
    assets/js/prodigious.script.js: {}
  dependencies:
    - core/jquery
    - core/jquery.once
    - core/drupal
